#!/usr/bin/env python3
"""
Generate a bitmap font atlas for ZAVOGLES-GUI.
Requires: pip install pillow
"""
from PIL import Image, ImageDraw, ImageFont
import os

# ========== CONFIG ==========
# استخدم المسار النسبي داخل المشروع
FONT_PATH = "tools/DejaVuSans.ttf"
# أو إذا ثبتت من Alpine: FONT_PATH = "/usr/share/fonts/dejavu/DejaVuSans.ttf"

ATLAS_SIZE = 512   # بدل 256
FONT_SIZE = 32     # بدل 16
OUTPUT_DIR = "assets"
GLYPHS_PER_ROW = 16
# ASCII printable range
START_CHAR = 32
END_CHAR = 127
# ============================

def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # جرب المسار الأول، إذا ما موجود استخدم المسار الثاني
    actual_font_path = FONT_PATH
    if not os.path.exists(actual_font_path):
        # fallback للمسار Alpine
        alpine_path = "/usr/share/fonts/dejavu/DejaVuSans.ttf"
        if os.path.exists(alpine_path):
            actual_font_path = alpine_path
            print(f"Using Alpine font: {alpine_path}")
        else:
            print(f"Font not found: {FONT_PATH}")
            print("Please download DejaVuSans.ttf and place it in tools/")
            print("Or run: apk add font-dejavu")
            return

    try:
        font = ImageFont.truetype(actual_font_path, FONT_SIZE)
    except OSError as e:
        print(f"Failed to load font: {e}")
        return

    atlas = Image.new("RGBA", (ATLAS_SIZE, ATLAS_SIZE), (0, 0, 0, 0))
    draw = ImageDraw.Draw(atlas)

    glyph_w = ATLAS_SIZE // GLYPHS_PER_ROW
    glyph_h = ATLAS_SIZE // GLYPHS_PER_ROW

    glyph_data = []

    for i, code in enumerate(range(START_CHAR, END_CHAR)):
        char = chr(code)
        col = i % GLYPHS_PER_ROW
        row = i // GLYPHS_PER_ROW
        x = col * glyph_w
        y = row * glyph_h

        # Measure
        bbox = draw.textbbox((0, 0), char, font=font)
        tw = bbox[2] - bbox[0]
        th = bbox[3] - bbox[1]
        # Draw centered in cell
        cx = x + (glyph_w - tw) // 2
        cy = y + (glyph_h - th) // 2 - bbox[1]  # adjust baseline

        draw.text((cx, cy), char, font=font, fill=(255, 255, 255, 255))

        # UV coords (0..1)
        uv_x = x / ATLAS_SIZE
        uv_y = y / ATLAS_SIZE
        uv_w = glyph_w / ATLAS_SIZE
        uv_h = glyph_h / ATLAS_SIZE

        # Pixel metrics
        advance = float(tw) if tw > 0 else float(FONT_SIZE * 0.5)
        if char == ' ':
            advance = float(FONT_SIZE * 0.4)

        glyph_data.append({
            'char': char,
            'uv_x': uv_x,
            'uv_y': uv_y,
            'uv_w': uv_w,
            'uv_h': uv_h,
            'width': float(tw),
            'height': float(th),
            'advance': advance,
            'x_offset': 0.0,
            'y_offset': 0.0,
        })

    # Save raw RGBA
    raw_path = os.path.join(OUTPUT_DIR, "font_atlas.rgba")
    with open(raw_path, "wb") as f:
        f.write(atlas.tobytes())
    print(f"Saved: {raw_path} ({ATLAS_SIZE}x{ATLAS_SIZE} RGBA)")

    # Save PNG for preview (optional)
    png_path = os.path.join(OUTPUT_DIR, "font_atlas.png")
    atlas.save(png_path)
    print(f"Saved preview: {png_path}")

    # Generate Rust code
    rust_path = os.path.join(OUTPUT_DIR, "font_glyphs.rs")
    with open(rust_path, "w") as f:
        f.write("// Auto-generated by tools/generate_font_atlas.py\n")
        f.write("use k1_gles::font::Glyph;\n\n")
        f.write("pub const FONT_GLYPHS: [Option<Glyph>; 96] = [\n")
        for g in glyph_data:
            if g['char'] == "'":
                ch_repr = "'\\''"
            else:
                ch_repr = repr(g['char'])
            # استخدم f-string نقية بدون .format()
            f.write(f"    // {ch_repr}\n")
            f.write(f"    Some(Glyph {{\n")
            f.write(f"        uv_x: {g['uv_x']:.6}f32,\n")
            f.write(f"        uv_y: {g['uv_y']:.6}f32,\n")
            f.write(f"        uv_w: {g['uv_w']:.6}f32,\n")
            f.write(f"        uv_h: {g['uv_h']:.6}f32,\n")
            f.write(f"        width: {g['width']:.1}f32,\n")
            f.write(f"        height: {g['height']:.1}f32,\n")
            f.write(f"        advance: {g['advance']:.1}f32,\n")
            f.write(f"        x_offset: {g['x_offset']:.1}f32,\n")
            f.write(f"        y_offset: {g['y_offset']:.1}f32,\n")
            f.write("    }),\n")
        f.write("];\n")
    print(f"Saved Rust glyph table: {rust_path}")

if __name__ == "__main__":
    main()
